"use client";

import { useState } from "react";
import { Download, FileText, AlertTriangle, Shield, Clock } from "lucide-react";
import jsPDF from 'jspdf';

export default function PDFReportGenerator({ analysisData }) {
    const [generating, setGenerating] = useState(false);

    const generatePDFReport = async () => {
        setGenerating(true);
        
        try {
            const pdf = new jsPDF();
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();
            let yPosition = 20;

            // Header
            pdf.setFontSize(20);
            pdf.setFont(undefined, 'bold');
            pdf.text('Legal Risk Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
            yPosition += 20;

            // Date
            pdf.setFontSize(10);
            pdf.setFont(undefined, 'normal');
            pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth - 20, yPosition, { align: 'right' });
            yPosition += 20;

            // Executive Summary
            pdf.setFontSize(16);
            pdf.setFont(undefined, 'bold');
            pdf.text('Executive Summary', 20, yPosition);
            yPosition += 10;

            pdf.setFontSize(10);
            pdf.setFont(undefined, 'normal');
            const summaryText = analysisData?.summary || 'This document has been analyzed for legal risks and compliance issues.';
            const splitSummary = pdf.splitTextToSize(summaryText, pageWidth - 40);
            pdf.text(splitSummary, 20, yPosition);
            yPosition += splitSummary.length * 5 + 10;

            // Risk Level
            pdf.setFontSize(14);
            pdf.setFont(undefined, 'bold');
            pdf.text('Overall Risk Level', 20, yPosition);
            yPosition += 10;

            const riskLevel = analysisData?.riskLevel || 'Medium';
            const riskColor = getRiskColor(riskLevel);
            pdf.setTextColor(riskColor.r, riskColor.g, riskColor.b);
            pdf.setFontSize(12);
            pdf.text(`Risk Level: ${riskLevel}`, 20, yPosition);
            pdf.setTextColor(0, 0, 0); // Reset to black
            yPosition += 15;

            // Key Risks
            if (analysisData?.risks && analysisData.risks.length > 0) {
                pdf.setFontSize(14);
                pdf.setFont(undefined, 'bold');
                pdf.text('Key Risk Areas', 20, yPosition);
                yPosition += 10;

                analysisData.risks.forEach((risk, index) => {
                    if (yPosition > pageHeight - 30) {
                        pdf.addPage();
                        yPosition = 20;
                    }

                    pdf.setFontSize(10);
                    pdf.setFont(undefined, 'bold');
                    pdf.text(`${index + 1}. ${risk.title}`, 25, yPosition);
                    yPosition += 7;

                    pdf.setFont(undefined, 'normal');
                    const riskDesc = pdf.splitTextToSize(risk.description, pageWidth - 50);
                    pdf.text(riskDesc, 30, yPosition);
                    yPosition += riskDesc.length * 5 + 5;
                });
            }

            // Recommendations
            if (analysisData?.recommendations && analysisData.recommendations.length > 0) {
                if (yPosition > pageHeight - 50) {
                    pdf.addPage();
                    yPosition = 20;
                }

                pdf.setFontSize(14);
                pdf.setFont(undefined, 'bold');
                pdf.text('Recommendations', 20, yPosition);
                yPosition += 10;

                analysisData.recommendations.forEach((rec, index) => {
                    if (yPosition > pageHeight - 30) {
                        pdf.addPage();
                        yPosition = 20;
                    }

                    pdf.setFontSize(10);
                    pdf.setFont(undefined, 'normal');
                    const recText = pdf.splitTextToSize(`${index + 1}. ${rec}`, pageWidth - 40);
                    pdf.text(recText, 25, yPosition);
                    yPosition += recText.length * 5 + 5;
                });
            }

            // Footer
            const totalPages = pdf.internal.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                pdf.setPage(i);
                pdf.setFontSize(8);
                pdf.setFont(undefined, 'normal');
                pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
                pdf.text('Generated by Legal Risk Radar', 20, pageHeight - 10);
            }

            // Save the PDF
            const fileName = `legal-risk-report-${new Date().toISOString().split('T')[0]}.pdf`;
            pdf.save(fileName);

        } catch (error) {
            console.error('PDF generation failed:', error);
            alert('Failed to generate PDF report');
        } finally {
            setGenerating(false);
        }
    };

    const getRiskColor = (level) => {
        switch (level.toLowerCase()) {
            case 'high': return { r: 239, g: 68, b: 68 };
            case 'medium': return { r: 245, g: 158, b: 11 };
            case 'low': return { r: 34, g: 197, b: 94 };
            default: return { r: 107, g: 114, b: 128 };
        }
    };

    return (
        <div className="bg-white rounded-lg shadow-lg p-6">
            <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                    <FileText className="text-blue-600" size={24} />
                    <h3 className="text-xl font-bold text-gray-900">Download Risk Report</h3>
                </div>
                <button
                    onClick={generatePDFReport}
                    disabled={generating}
                    className="inline-flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
                >
                    {generating ? (
                        <>
                            <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>
                            Generating...
                        </>
                    ) : (
                        <>
                            <Download size={16} />
                            Download PDF
                        </>
                    )}
                </button>
            </div>

            <div className="grid md:grid-cols-3 gap-4 mb-6">
                <div className="bg-red-50 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                        <AlertTriangle className="text-red-600" size={16} />
                        <span className="text-sm font-semibold text-red-800">High Risk Items</span>
                    </div>
                    <p className="text-2xl font-bold text-red-600">
                        {analysisData?.risks?.filter(r => r.level === 'high').length || 0}
                    </p>
                </div>

                <div className="bg-yellow-50 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                        <Clock className="text-yellow-600" size={16} />
                        <span className="text-sm font-semibold text-yellow-800">Medium Risk Items</span>
                    </div>
                    <p className="text-2xl font-bold text-yellow-600">
                        {analysisData?.risks?.filter(r => r.level === 'medium').length || 0}
                    </p>
                </div>

                <div className="bg-green-50 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                        <Shield className="text-green-600" size={16} />
                        <span className="text-sm font-semibold text-green-800">Low Risk Items</span>
                    </div>
                    <p className="text-2xl font-bold text-green-600">
                        {analysisData?.risks?.filter(r => r.level === 'low').length || 0}
                    </p>
                </div>
            </div>

            <div className="text-sm text-gray-600">
                <p>The PDF report will include:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                    <li>Executive summary of legal risks</li>
                    <li>Detailed risk analysis with severity levels</li>
                    <li>Actionable recommendations</li>
                    <li>Compliance checklist</li>
                </ul>
            </div>
        </div>
    );
}